// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfwzhsnofofxvocwvwxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmd3poc25vZm9meHZvY3d2d3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Mzg3OTEsImV4cCI6MjA3MjQxNDc5MX0.Wtnv-h5G7EWZoLSQdMtR1YazH3gcuPq11fVAWOHqsmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});